print("Hello, World!")
print("Hello Again!")
print("I like typing this.")
print("This is Fun.")
print('yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("I said do not touch this.")
print("This is python class \n in Tarzan Skills")
print("Hello my name is Salina \t My qualification is \\n Bachelor of Engg")
print("root->node->child")
print("root","node","child","rose",sep= '->')
print("Hello",end=' ')
print("World")